STD = -std=c++20 -DEIGEN_FFTW_DEFAULT
CXX = g++

W_FLAGS = -Wall -Wpedantic
W_FLAGS+= -Wno-deprecated-declarations
W_FLAGS+= -Wno-format-security
W_FLAGS+= -Wno-deprecated-enum-compare-conditional
W_FLAGS+= -Wno-deprecated-anon-enum-enum-conversion

OPTIMISE_FLAGS = -Ofast -ffp-contract=fast -DNDEBUG
OPTIMISE_FLAGS+= -mavx2 -mfma -march=native
LIBSEAHORSE = -L./seahorse/lib/ -lseahorse

DEBUG_FLAGS = -O0 -UNDEBUG
LIBSEAHORSED = -L./seahorse/lib/ -lseahorsed

USE_FFTW = -lfftw3 -lfftw3f -lfftw3l #-L/usr/local/lib

INCLUDE_PATHS = -I./
INCLUDE_PATHS += -I./seahorse
INCLUDE_PATHS += -I./libs/eigen
INCLUDE_PATHS += -I./libs/raylib/src
#INCLUDE_PATHS += -I/usr/local/include

LIBRAYLIB = -L./libs/raylib/src -lraylib
FRAMEWORKS = -framework CoreVideo
FRAMEWORKS+= -framework IOKit
FRAMEWORKS+= -framework Cocoa
FRAMEWORKS+= -framework GLUT
FRAMEWORKS+= -framework OpenGL

# Colours for logging
GREEN='\033[92m'
RED='\033[91m'
NC='\033[0m'

define generate_source
	@echo ${GREEN}[GENERATING SOURCE STRING]${NC} $(1)...
	@ $(RUN) xxd -i -u -n sourceFile $(1).cpp > $(1).asString
endef

define clean_up_source
    @ find . -name '*.asString' | xargs rm
endef